### PR TITLE
Upload updated Excel Template V021 with new Read-Me table

### PR DESCRIPTION
**Pull request by Maja4Dev**
Updated Excel Template Version EN V021 of 24.05.2024 which is consistent with updated Technical Notes (= Excel table READ-ME).

### CODE REVIEW

**Comment by Maja4Dev** [comment]
After upload, the links to this template on the other pages have to be changed so that they link to this new version.

**Review by fretchen — CHANGES_REQUESTED** [review]
It would be *much* better to really update the excel template and not do versioning within the file name.

The advantages are:

- No links need to be updated.
- We have a clear track record of the changes to the document (all within git records).

The file name is really a very poor place to keep the version as it is constantly changed by users. Better ways for versioning:

- If you want to have a note of the version in the excel file (which might be a good idead), it might be best noted in a specific excel sheet, which describes the history.
- As soon as the tasks for the [milestone of v1](https://github.com/openkfw/open-geodata-model/milestone/2) are fulfilled we can do a release where the how documents including templates are tagged as release v1.

So I would *strongly* recommend to change the filename such that it overwrites the old file.

**Comment by Jo-Schie** [comment]
> It would be _much_ better to really update the excel template and not do versioning within the file name.
> 
> The advantages are:
> 
> * No links need to be updated.
> * We have a clear track record of the changes to the document (all within git records).
> 
> The file name is really a very poor place to keep the version as it is constantly changed by users. Better ways for versioning:
> 
> * If you want to have a note of the version in the excel file (which might be a good idead), it might be best noted in a specific excel sheet, which describes the history.
> * As soon as the tasks for the [milestone of v1](https://github.com/openkfw/open-geodata-model/milestone/2) are fulfilled we can do a release where the how documents including templates are tagged as release v1.
> 
> So I would _strongly_ recommend to change the filename such that it overwrites the old file.

Sounds very logical to me. I would suggest adding a new tab "version and changelog" where we track the changes to the model also verbally within the model.

**Comment by fretchen** [comment]
Was made redundant by #66

**Pull request closed without merging**
