### PR TITLE
Split the main

### PR DESCRIPTION
**Pull request by fretchen**
This first PR provides a first attempt to split the file as suggested in #41 . However, there is still an open problem of what to do with the section _Link to the model template_

I currently put it into an extra file, but this is just very strange as the file is basically empty. So would much rather keep it nicely highlighted in the `ìndex.md` file at the end. @Maja4Dev ?

### CODE REVIEW

**Comment by fretchen** [comment]
As suggested by @Jo-Schie I updated the navigation.
Because I could not bare the lonely single file for the link to the template I moved the link into an admonition.
Live version [here](https://fretchen.github.io/open-geodata-model/).

@Jo-Schie  if this is fine by you feel free to approve and merge or simply provide feedback here...

**Comment by Maja4Dev** [comment]
We don't have a "Link to the model template". We need a separate page "Project Location Model Templates and sample ToR (EN/FR)" which I want then to fill with content and links.

**Comment by fretchen** [comment]
> We don't have a "Link to the model template". We need a separate page "Project Location Model Templates and sample ToR (EN/FR)" which I want then to fill with content and links.

Create a new issue #47 which can be closed once the new text is available.

**Review by Jo-Schie — COMMENTED** [review]
looks good

**Pull request merged**
